# Names of bioclim variables

bioclimnames <- c('bio1' = 'paste("Mean annual temperature (",degree,"C)")',
                  'bio2' = 'paste("Mean diurnal temperature range (",degree,"C)")',
                  'bio3' = 'Isothermality (%)',
                  'bio4' = 'Temperature seasonality (SD*100)',
                  'bio5' = 'paste("Maximum temperature of warmest month (",degree,"C)")',
                  'bio6' = 'paste("Minimum temperature of coldest month (",degree,"C)")',
                  'bio7' = 'paste("Annual temperature range (",degree,"C)")',
                  'bio8' = 'paste("Mean temperature of wettest quarter (",degree,"C)")',
                  'bio9' = 'paste("Mean temperature of driest quarter (",degree,"C)")',
                  'bio10' = 'paste("Mean temperature of warmest quarter (",degree,"C)")',
                  'bio11' = 'paste("Mean temperature of coldest quarter (",degree,"C)")',
                  'bio12' = 'Annual precipitation (mm)',
                  'bio13' = 'Precipitation of wettest month (mm)',
                  'bio14' = 'Precipitation of driest month (mm)',
                  'bio15' = 'Precipitation seasonality (CV)',
                  'bio16' = 'Precipitation of wettest quarter (mm)',
                  'bio17' = 'Precipitation of driest quarter (mm)',
                  'bio18' = 'Precipitation of warmest quarter (mm)',
                  'bio19' = 'Precipitation of coldest quarter (mm)')